# Generated by Django 4.2.16 on 2026-06-09 02:58

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=store.models.generate_order_number, editable=False, max_length=20, unique=True, verbose_name='Número de orden')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de pago'), ('paid', 'Pagado'), ('processing', 'En preparación'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('full_name', models.CharField(max_length=120, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('address_line', models.CharField(max_length=200, verbose_name='Dirección')),
                ('city', models.CharField(max_length=80, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=80, verbose_name='Estado / Provincia')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Código postal')),
                ('country', models.CharField(default='MX', max_length=2, verbose_name='País (código)')),
                ('country_name', models.CharField(default='México', max_length=80, verbose_name='País')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal (IVA incl.)')),
                ('iva_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA incluido')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Envío')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('payment_method', models.CharField(blank=True, choices=[('stripe', 'Stripe (tarjeta)'), ('mercadopago', 'MercadoPago'), ('simulated', 'Simulado (prueba)')], max_length=20, verbose_name='Método de pago')),
                ('payment_reference', models.CharField(blank=True, max_length=200, verbose_name='Referencia de pago')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagado el')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('hoodie_alo', 'Hoodie Alo Accolade'), ('crewneck', 'Crewneck'), ('hoodie_essentials', 'Hoodie Essentials'), ('playera_essentials', 'Playera Essentials')], max_length=40, verbose_name='Categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('fabric', models.CharField(blank=True, help_text='Ej. Algodón peinado 380gsm, interior afelpado.', max_length=200, verbose_name='Tela / material')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (IVA incluido)')),
                ('badge', models.CharField(blank=True, help_text='Ej. Bestseller, Nuevo, Edición limitada.', max_length=30, verbose_name='Etiqueta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Color')),
                ('hex_code', models.CharField(default='#1a1a1a', help_text='Ej. #000000', max_length=7, verbose_name='Código HEX')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/colors/', verbose_name='Imagen del color')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='store.product')),
            ],
            options={
                'verbose_name': 'Color de producto',
                'verbose_name_plural': 'Colores de producto',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=140, verbose_name='Texto alternativo')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Principal')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['-is_primary', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/features/', verbose_name='Imagen')),
                ('icon', models.CharField(blank=True, help_text='Ej. 🧵, 🏷️, 🧥', max_length=20, verbose_name='Icono (emoji o nombre)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='store.product')),
            ],
            options={
                'verbose_name': 'Característica destacada',
                'verbose_name_plural': 'Características destacadas',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120, verbose_name='Producto')),
                ('color', models.CharField(blank=True, max_length=40, verbose_name='Color')),
                ('size', models.CharField(blank=True, max_length=4, verbose_name='Talla')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total línea')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
            options={
                'verbose_name': 'Artículo del pedido',
                'verbose_name_plural': 'Artículos del pedido',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=4, verbose_name='Talla')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Inventario')),
                ('sku', models.CharField(blank=True, max_length=40, unique=True, verbose_name='SKU')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.productcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'verbose_name': 'Variante (color + talla)',
                'verbose_name_plural': 'Variantes (color + talla)',
                'ordering': ['color__sort_order', 'size'],
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
